[package]
name = "lza"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "*"
[dependencies.miniz_oxide]
version = "*"
optional = true

[features]
default = ["writer"]
writer = ["miniz_oxide"]